import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generates a professional PDF invoice for a restaurant order.
 * @param {Object} order - The order object from the backend
 * @param {Object} tableInfo - Optional table details (number)
 * @param {Object} staffInfo - Optional staff details (name)
 */
export const generateInvoicePDF = (order, tableInfo = null, staffInfo = null) => {
    const doc = new jsPDF();
    const orderNo = order.orderNo || "INV-TEMP";
    const date = new Date(order.createdAt || Date.now());
    
    // --- Brand Header ---
    doc.setFillColor(15, 14, 40); // Matches dashboard bg
    doc.rect(0, 0, 210, 45, 'F');
    
    doc.setFontSize(28);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("OCEANBREEZE", 14, 25);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Premium Dining Experience", 14, 32);
    
    doc.setFontSize(14);
    doc.text("INVOICE", 170, 25, { align: "right" });
    doc.setFontSize(9);
    doc.text(`#${orderNo}`, 170, 32, { align: "right" });

    // --- Customer & Order Info ---
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("ORDER INFORMATION", 14, 55);
    
    doc.setFont("helvetica", "normal");
    doc.text(`Date: ${date.toLocaleDateString()}`, 14, 62);
    doc.text(`Time: ${date.toLocaleTimeString()}`, 14, 67);
    doc.text(`Table: ${tableInfo?.tableNumber || order.tableId?.tableNumber || "N/A"}`, 14, 72);
    
    doc.text("ISSUED BY", 140, 55);
    doc.text(`Staff: ${staffInfo?.name || order.staffId?.name || "Customer"}`, 140, 62);
    doc.text("OceanBreeze Restaurant", 140, 67);

    // --- Items Table ---
    const tableColumn = ["Description", "Price (LKR)", "Qty", "Total (LKR)"];
    const tableRows = (order.items || []).map(item => [
        item.name,
        Number(item.price).toLocaleString(),
        item.qty,
        (item.price * item.qty).toLocaleString()
    ]);

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 80,
        theme: 'grid',
        headStyles: { 
            fillColor: [64, 140, 140], // Matches theme primary
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            halign: 'center'
        },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { halign: 'right', cellWidth: 35 },
            2: { halign: 'center', cellWidth: 20 },
            3: { halign: 'right', cellWidth: 35 }
        },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        styles: { font: "helvetica", fontSize: 9 }
    });

    // --- Financial Summary ---
    const finalY = doc.lastAutoTable.finalY + 10;
    const subtotal = order.subtotal || (order.items || []).reduce((acc, i) => acc + (i.price * i.qty), 0);
    const tax = order.tax || Math.round(subtotal * 0.1);
    const total = order.total || (subtotal + tax);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Subtotal:", 140, finalY);
    doc.text(`${subtotal.toLocaleString()}`, 196, finalY, { align: "right" });
    
    doc.text("VAT/Tax (10%):", 140, finalY + 7);
    doc.text(`${tax.toLocaleString()}`, 196, finalY + 7, { align: "right" });
    
    doc.setDrawColor(200, 200, 200);
    doc.line(140, finalY + 11, 196, finalY + 11);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(64, 140, 140);
    doc.text("GRAND TOTAL:", 140, finalY + 19);
    doc.text(`LKR ${total.toLocaleString()}`, 196, finalY + 19, { align: "right" });

    // --- Footer ---
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "italic");
    doc.text("Thank you for dining with us! Visit again soon.", 105, 280, { align: "center" });
    doc.text("Generated by OceanBreeze POS System", 105, 285, { align: "center" });

    doc.save(`OceanBreeze_Invoice_${orderNo}.pdf`);
};
